Create HW8
itsulias/urban-fortnight pull request #11
Opened 2022-06-09 08:21 UTC by itsulias

2022-06-09 13:57 UTC, dmitrii-kruglov requested changes
нужно доработать.

2022-06-09 13:57 UTC, dmitrii-kruglov commented on HW8
> + bool login(string log) {
еще нужно логин проверить

2022-06-09 14:00 UTC, itsulias commented
> нужно доработать.

Сколько у меня есть времени, чтобы доработать?

2022-06-15 16:06 UTC, dmitrii-kruglov commented
> > нужно доработать.
> 
> Сколько у меня есть времени, чтобы доработать?

были все эти дни.. Уже нельзя доработать

2022-06-15 16:06 UTC, closed without merging